/** Central light-only Ant Design theme for Devtools Plus. */
export function createDevtoolsTheme(accentColor) {
  const palette = {
    text: "#172b3f",
    textSecondary: "#63778b",
    textTertiary: "#8a9bad",
    border: "#d9e3ec",
    borderSecondary: "#e9eef3",
    layout: "#f4f7fa",
    container: "#ffffff",
    elevated: "#ffffff",
    control: "#ffffff",
    hover: "#f7fbfe",
    selected: "#eef6fb",
    selectHover: "#f4faf8",
    selectSelected: "#e8f6f1",
    selectSelectedText: "#2d6f62",
    shadow: "0 20px 48px rgba(24, 45, 66, 0.14), 0 3px 10px rgba(24, 45, 66, 0.06)",
  };

  return {
    cssVar: {prefix: "ddp", key: "dash-devtools-plus"},
    token: {
      colorPrimary: accentColor,
      colorInfo: accentColor,
      colorText: palette.text,
      colorTextSecondary: palette.textSecondary,
      colorTextTertiary: palette.textTertiary,
      colorBorder: palette.border,
      colorBorderSecondary: palette.borderSecondary,
      colorBgLayout: palette.layout,
      colorBgContainer: palette.container,
      colorBgElevated: palette.elevated,
      colorFillSecondary: "rgba(23, 43, 63, 0.05)",
      colorFillTertiary: "rgba(23, 43, 63, 0.035)",
      borderRadius: 10,
      borderRadiusLG: 14,
      controlHeight: 40,
      fontSize: 14,
      fontSizeSM: 13,
      lineHeight: 1.55,
      boxShadowSecondary: palette.shadow,
      fontFamily: '"Aptos", "Noto Sans SC", "Segoe UI", sans-serif',
    },
    components: {
      Button: {
        controlHeight: 36,
        borderRadius: 9,
        defaultBg: palette.control,
        defaultBorderColor: palette.border,
        defaultColor: palette.textSecondary,
        defaultHoverBg: palette.hover,
        defaultShadow: "0 1px 2px rgba(24, 45, 66, 0.04)",
        fontWeight: 600,
      },
      Drawer: {colorBgElevated: palette.container, zIndexPopup: 100001},
      Input: {
        colorBgContainer: palette.control,
        activeBorderColor: accentColor,
        hoverBorderColor: "#b8cee0",
        activeShadow: `0 0 0 3px ${accentColor}18`,
        paddingBlock: 8,
      },
      Select: {
        colorBgContainer: palette.control,
        activeBorderColor: accentColor,
        hoverBorderColor: "#b8cee0",
        activeOutlineColor: `${accentColor}18`,
        optionActiveBg: palette.selectHover,
        optionSelectedBg: palette.selectSelected,
        optionSelectedColor: palette.selectSelectedText,
        optionSelectedFontWeight: 600,
        selectorBg: palette.control,
        zIndexPopup: 100002,
      },
      Segmented: {
        trackBg: "#f1f5f8",
        trackPadding: 3,
        itemColor: palette.textSecondary,
        itemHoverColor: palette.text,
        itemHoverBg: palette.hover,
        itemActiveBg: palette.selected,
        itemSelectedBg: "#ffffff",
        itemSelectedColor: accentColor,
      },
      Tabs: {
        inkBarColor: accentColor,
        itemColor: palette.textSecondary,
        itemHoverColor: "#294a65",
        itemActiveColor: accentColor,
        itemSelectedColor: accentColor,
        titleFontSize: 14,
        horizontalItemGutter: 30,
        horizontalItemPadding: "13px 2px 12px",
      },
      Card: {colorBgContainer: palette.container, bodyPaddingSM: 17},
      Table: {
        colorBgContainer: palette.container,
        headerBg: "#f7f9fb",
        headerColor: palette.textSecondary,
        headerSplitColor: "transparent",
        headerSortActiveBg: palette.selected,
        headerSortHoverBg: palette.selected,
        bodySortBg: "#fbfdfe",
        rowHoverBg: palette.hover,
        borderColor: palette.borderSecondary,
        cellPaddingBlockSM: 12,
        cellPaddingInlineSM: 12,
        cellFontSizeSM: 14,
        headerBorderRadius: 10,
      },
      Pagination: {
        itemSize: 34,
        itemBg: "transparent",
        itemLinkBg: "transparent",
        itemActiveBg: `${accentColor}18`,
        itemActiveColor: accentColor,
      },
      Tag: {borderRadiusSM: 6, fontSizeSM: 12},
      Tooltip: {borderRadius: 8},
      Popover: {borderRadiusLG: 12, zIndexPopup: 100030},
    },
  };
}
